# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 414f40222929798ff8fa167aac7926781f093dfc40f39941314b869696ff26fb98f4ce68ca6ed2475d09c7d0250632965944dc399c45e2425974b985b976c5f8

test:
  secret_key_base: 0e3226cd1eaccbec61e31eba59e608c24b8f803c52efbaab77e6cfaa7bfb9f9348bd0130105ee7f4bfdd7b6c006999956dd612158d723bb4d7a5a170ec0f0fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
